image: Previous Visual Studio 2019

build: off

clone_folder: c:\gopath\src\github.com\go-python\gopy

cache:
  - '%LocalAppData%\\go-build'
  - '%LocalAppData%\\pip'

branches:
  only:
    - master

environment:
  GOPATH: C:\gopath
  GOROOT: C:\go121
  GOPY_APPVEYOR_CI: '1'
  GOTRACEBACK: 'crash'
  CPYTHON3DIR: "C:\\Python311-x64"
  PATH: '%GOPATH%\bin;%GOROOT%\bin;%CPYTHON3DIR%;%CPYTHON3DIR%\\Scripts;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%'

stack: go 1.21

build_script:
  - python --version
  - "%CPYTHON3DIR%\\python --version"
  - "%CPYTHON3DIR%\\python -m pip install --upgrade pip"
  - "%CPYTHON3DIR%\\python -m pip install cffi"
  - "%CPYTHON3DIR%\\python -m pip install pybindgen"
  - go version
  - go env
  - go get -v -t ./...
  - go install golang.org/x/tools/cmd/goimports@latest

test_script:
  - go test ./...
