// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.11.1"
	GitCommit   = "777bfa7"          // the commit JUST BEFORE the release
	VersionDate = "2024-07-16 17:55" // UTC
)
