// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.12.0"
	GitCommit   = "0f3ab52"          // the commit JUST BEFORE the release
	VersionDate = "2025-03-04 23:47" // UTC
)
